# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CamadaBuffer
                                 A QGIS plugin
 CamadaBuffer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-07-15
        copyright            : (C) 2024 by Prof Cazaroli
        email                : prof.cazaroli@geoone.com.br
 ***************************************************************************/
"""

def classFactory(iface):
    from .CamadaBuffer import CamadaBuffer
    return CamadaBuffer(iface)
